name: amap_base_navi
description: Fully Functional AMap Flutter Plugin. Based on AndroidView/UiKitView.
version: 0.4.0+1
author: yohom <382146139@qq.com>
homepage: https://github.com/yohom/amap_base_flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
#  amap_base_core: any
  amap_base_core:
    path: ../core
  flushbar:
    git:
      url: https://github.com/AndreHaueisen/flushbar
      ref: dev_version

flutter:
  plugin:
    androidPackage: me.yohom.amapbasenavi
    pluginClass: AMapBaseNaviPlugin

  assets:
    - images/
